### ISSUE TITLE
`yo salsa` asks a non-question at startup expecting an answer.

### ISSUE THREAD

**Issue by realyze** [salsita/generator-salsa#1]
mac-air, OS X 10.8.3

running `yo salsa` gives me:

[?] ==========================================================================
We're constantly looking for ways to make yo better! 
May we anonymously report usage statistics to improve the tool over time? 
More info: yeoman.io/insight.html & http://yeoman.io
==========================================================================: 

What am I supposed to say? :-)

**Comment by iki** [comment]
This is yeoman anonymous usage reporting using https://github.com/yeoman/insight. Feel free to make your choice at `npm install yeoman -g` time, or [later](http://stackoverflow.com/questions/19945246/how-to-prevent-yeoman-from-sending-anonymous-statistics).
